name: Build Image

on:
  push:
    tags:
      - "v*"

jobs:
  docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    
    steps:
      - name: Get Secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{secrets.BW_ACCESS_TOKEN}}
          base_url: https://vault.bitwarden.eu
          secrets: |
            eb3ecf3c-07b8-427d-b5e6-b20e016807d3 > DOCKER_USERNAME
            81e3ffa4-e522-4a25-93bf-b20e01682fcf > DOCKER_PASSWORD
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Docker Auth
        uses: docker/login-action@v3
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}
      
      - name: Build image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vanvanni/gorestic:latest
